name: Release Excel Chart

on:
  push:
    tags:
      - 'docker/excel/0.[0-9]+.[0-9]+*'

jobs:
  release:
    name: Run release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.8'

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.11.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker login
        run: |
          echo '${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}' | docker login ghcr.io --username ${{ secrets.GH_USERNAME }} --password-stdin

      - name: Parse tag
        id: tag
        run: |
          echo "RELEASE_VERSION=$(echo ${GITHUB_REF#refs/*/docker/excel/})" >> $GITHUB_OUTPUT

      - name: Package and push Helm Chart
        run: |
          sed -i 's/tag: .*/tag: "${{ steps.tag.outputs.RELEASE_VERSION }}"/' deployments/ytsaurus-excel-chart/values.yaml
          helm package deployments/ytsaurus-excel-chart/ --version ${{ steps.tag.outputs.RELEASE_VERSION }}
          helm push ytsaurus-excel-chart-${{ steps.tag.outputs.RELEASE_VERSION }}.tgz oci://ghcr.io/ytsaurus

      - name: Build and push Exporter Docker image
        run: |
          cd exporter/build/docker
          make docker-release IMAGE_TAG=${{ steps.tag.outputs.RELEASE_VERSION }}

      - name: Build and push Uploader Docker image
        run: |
          cd uploader/build/docker
          make docker-release IMAGE_TAG=${{ steps.tag.outputs.RELEASE_VERSION }}
